### ISSUE TITLE
How to send contracts to the node?

### ISSUE THREAD

**Issue by daemonslayer** [Capgemini-AIE/ethereum-docker#32]
I can't find any instructions to deploy contracts to the docker-node. Is there a way to do so using truffle-contract or any other method ?

**Comment by manojpramesh** [comment]
you can deploy contracts to the docker-node just like you do with regular ethereum nodes. Connect to the node using `<your-ip/localhost>:8545` and deploy contracts using truffle. You can also connect to the console using `docker exec -it bootstrap geth attach ipc://root/.ethereum/devchain/geth.ipc` and deploy the contract using web3.

**Comment by daemonslayer** [comment]
I am using these settings: 
```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" // Match any network id
    },
    ropsten: {
      host: "localhost",
      port: 8545,
      network_id: "3" // Match any network id
    }
  }
};

```

This is what bootstrap said : 
```
bootstrap    | INFO [08-31|12:22:48] HTTP endpoint opened: http://0.0.0.0:8545 
```
But on running `truffle migrate`, it says :
```
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```

**Comment by daemonslayer** [comment]
Thanks. I got it working, but I am having this error.
```
Error: insufficient funds for gas * price + value
```
How can I get funds in a private node ?

**Comment by manojpramesh** [comment]
There are several ways to get funds.

You can either add the account address and funds in the genesis file or start mining in any of the node which will add funds to the coinbase.

**Comment by daemonslayer** [comment]
Can you please send me the command for mining that will add funds to particular wallet?

**Comment by manojpramesh** [comment]
Connect to the node
`docker exec -it bootstrap geth attach ipc://root/.ethereum/devchain/geth.ipc`
Start mining
`miner.start()`
Stop mining
`miner.stop()`

Starting the miner for the first time will generate DAG. It will take some time to complete. After generating the DAG, new blocks will be mined and ethers will be added to the coinbase.

I will suggest you to start the mining only when needed. Otherwise it will generate empty blocks and also will increase the difficulty pretty quickly which you do want in a test network.

**Comment by daemonslayer** [comment]
I put funds in the genesis file for the required account and now it doesn't give the error that it gave before. The contract deployment gets initiated but it is taking too long.

Logs:
```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xd60bb1ed968a864ac57b0a82dbd8a817c6c220aef7c6f68409c7df6d322148e0
```
```
netstats     | 2017-08-31 08:22:06.166 [API] [STA] Stats from: 5424Dcaec129
bootstrap    | INFO [08-31|13:52:21] Submitted contract creation              fullhash=0xd60bb1ed968a864ac57b0a82dbd8a817c6c220aef7c6f68409c7df6d322148e0 contract=0xb36b63b37c8493bd236b2cc2eec4fb2a59e602c3
netstats     | 2017-08-31 08:22:21.864 [API] [TXS] Pending: 1 from: bootstrap
netstats     | 2017-08-31 08:22:51.381 [API] [STA] Stats from: bootstrap
```
In testrpc, all my contracts take very little time in getting deployed. Here, even the migration account is taking very long. I have been waiting for more than 20 minutes for it to complete. Is this how it is meant to behave or is there something wrong?

**Comment by manojpramesh** [comment]
The transaction which you have submitted is pending because, there is no node mining in your network. Testrpc is a simulated network and it will handle mining as transactions come.

You will need to start mining in any of your nodes to commit a transaction. Please check the previous comment for steps.

**Comment by daemonslayer** [comment]
Does using the saved DAGs from [here](https://github.com/Capgemini-AIE/ethereum-docker#21-use-existing-dag) help? 
Also, can you please tell me where this DAG came from and how I can save my DAG after I perform mining?

**Comment by d-barker** [comment]
@daemonslayer regarding the DAG, the DAG is a 1 GB file so you will not find a copy in GitHub. The best place to get a copy of the DAG is to start mining and once the first block is created, you can then copy the first DAG out using the docker cp command; 

To start mining:

`docker exec -it ethereumdocker_eth_1 geth attach ipc://root/.ethereum/devchain/geth.ipc`

Then

`miner.start()`

Depending on your machine you will have to wait some time for the first block to be created. Once cerated run:

`miner.stop()`

Then you can copy the DAG by doing the following (assuming you are currently in the root of the ethereum-docker directory, it will copy the full-R23-00...00 file into the monitored-geth-client directory.

`docker cp ethereumdocker_eth_1:/root/.ethash/full-R23-0000000000000000 monitored-geth-client`

You can then add the following line to the Dockerfile in the monitored-geth-client directory, I placed this above the ADD start.sh /root/start.sh line.

`ADD full-R23-0000000000000000 /root/.ethash/full-R23-0000000000000000`

Some other changes to the docker file that you might need, 

1.  First line, remove the client-go version number, we need the latest as it is using alpine 3.6
2. Now that we are using the latest version, we now need to add nodejs-npm to package install something like the following:
   `RUN apk update &&\
    apk add git nodejs nodejs-npm bash perl`
    Nodejs no longer includes (as of v3.6) the package manager (npm)

Once you make the changes you will need to rebuild the compose; run the following commands:

`docker-compose down`

Then rebuild the images:

`docker-compose build`

Now we are using ethereum 1.7 and alpine 3.6 and we have  DAG that speeds up the starting of the network enormously (a few seconds compared to many minutes)

Another note is the accounts do not have a password, so to unlock to create a digital contract you can do something like the following (assuming you are on a test network; otherwise decrease the timeout):

`docker exec -it ethereumdocker_eth_1 geth attach ipc://root/.ethereum/devchain/geth.ipc
personal.unlockAccount(personal.listAccounts[0],"",150000)`
